# Generated by Django 2.2.4 on 2019-09-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreNews2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('tags', models.TextField(default='sobhan esfandyari,')),
                ('choice', models.CharField(choices=[('chw', 'computer hardware news'), ('csw', 'computer software news'), ('pir', 'iran politics'), ('pin', 'international politics')], default='csw', max_length=3)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('main_pic', models.ImageField(upload_to='images/')),
                ('brief', models.TextField(max_length=255)),
                ('article', models.TextField()),
            ],
        ),
    ]
