# Generated by Django 2.2 on 2019-08-29 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0015_remove_newsmodel_news_more_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('main_pic', models.ImageField(upload_to='images/')),
                ('brief', models.TextField(max_length=255)),
                ('article', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.LoginFormModel')),
            ],
        ),
    ]
