# Generated by Django 2.2 on 2019-08-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenews',
            old_name='autor',
            new_name='author',
        ),
    ]
