# Generated by Django 2.2 on 2019-08-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190829_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenews',
            name='slug',
            field=models.SlugField(default='prepare something here', unique=True),
            preserve_default=False,
        ),
    ]
