# Generated by Django 2.2.4 on 2019-08-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_prenews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenews',
            name='choice',
            field=models.CharField(choices=[('chw', 'computer hardware news'), ('csw', 'computer software news'), ('pir', 'iran politics'), ('pin', 'international politics')], default='csw', max_length=3),
        ),
        migrations.AddField(
            model_name='prenews',
            name='tags',
            field=models.TextField(default='sobhan esfandyari,'),
        ),
    ]
