# Generated by Django 2.2 on 2019-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginformmodel',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
