# Generated by Django 2.2 on 2019-08-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_loginformmodel_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('news_pic', models.ImageField(upload_to='')),
                ('news_par', models.CharField(max_length=10000)),
            ],
        ),
    ]
