# Generated by Django 2.2 on 2019-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
