# Generated by Django 2.2 on 2019-08-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190819_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
