# Generated by Django 2.2 on 2019-08-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190820_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_par',
            field=models.TextField(max_length=10000),
        ),
    ]
