# Generated by Django 2.2 on 2019-08-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contactformmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='contactformmodel',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
