# Generated by Django 2.2 on 2019-08-23 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190823_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
