# Generated by Django 2.2 on 2019-08-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactformmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmodel',
            name='date',
        ),
    ]
