# Generated by Django 2.2 on 2019-08-23 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_contactformmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
