# Generated by Django 2.2 on 2019-08-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contactformmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
