# Generated by Django 2.2 on 2019-08-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190823_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginformmodel',
            name='comment',
        ),
    ]
