# Generated by Django 2.2 on 2019-08-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190823_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='news_more_pic',
        ),
    ]
